# Generated by Django 2.2.3 on 2019-09-27 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_remove_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
