# Generated by Django 2.2.3 on 2019-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20190927_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
