# Generated by Django 2.2.3 on 2019-09-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markettingpreference',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
