# Generated by Django 2.2.3 on 2019-09-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_markettingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markettingpreference',
            old_name='update',
            new_name='updated',
        ),
    ]
