# Generated by Django 2.2.6 on 2019-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20191030_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='img/avaatr-2.png', upload_to='profile/'),
        ),
    ]
