# Generated by Django 2.2.3 on 2019-09-04 08:00

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=category.models.upload_filename_ext),
        ),
    ]
