# Generated by Django 2.2.3 on 2019-09-03 17:21

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190903_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_filename_ext),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_filename_ext),
        ),
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=products.models.upload_filename_ext),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Unique one', max_length=200, unique=True),
        ),
    ]
