# Generated by Django 2.2.3 on 2019-09-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190904_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='sub_category',
        ),
    ]
