# Generated by Django 2.2.3 on 2019-09-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190904_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='brand_name',
        ),
    ]
